version: '2'

services:
    ###########################################################################
    # BoB.
    dev-camera-bob2:
        container_name: dev-camera-bob2
        image: $DOCKER_IMAGE_DEV_CAMERA_BOB
        restart: always
        ipc: "host"
        network_mode: "host"
        environment:
        - DISPLAY=$DISPLAY
        volumes:
        - /tmp:/tmp
        cap_add:
        - SYS_NICE
        entrypoint: ""
        command: "nice -n -5 /usr/bin/dlv-device-camera-bob --cid=110 --hostip=192.168.1.1 --bobip=192.168.1.2 --name.i420=bob2.i420 --name.argb=bob2.argb"

    x264-ll-rec-bob2:
        container_name: x264-lossless-recorder-bob2
        build:
            context: https://github.com/chalmers-revere/opendlv-video-x264-recorder.git#v0.0.1
            dockerfile: Dockerfile.amd64
        restart: always
        ipc: "host"
        network_mode: "host"
        volumes:
        - /tmp:/tmp
        - $HOME/recordings/bob2:/recordings
        working_dir: /recordings
        cap_add:
        - SYS_NICE
        entrypoint: ""
        command: "nice -n -6 /usr/bin/opendlv-video-x264-recorder --id=2 --name=bob2.i420 --width=1104 --height=624"

    ###########################################################################
    # Basler.
    dev-camera-basler1:
        container_name: dev-camera-basler1
        build:
            context: https://github.com/chalmers-revere/opendlv-device-camera-pylon.git#v0.0.1
            dockerfile: Dockerfile.amd64
        restart: always
        network_mode: "host"
        ipc: "host"
        environment:
        - DISPLAY=$DISPLAY
        volumes:
        - /tmp:/tmp
        cap_add:
        - SYS_NICE
        entrypoint: ""
        command: "nice -n -7 /usr/bin/opendlv-device-camera-pylon --camera=0 --width=1024 --height=768 --offsetX=640 --offsetY=500 --fps=15 --name.i420=basler1.i420 --name.argb=basler1.argb"

    x264-ll-rec-basler1:
        container_name: x264-lossless-recorder-basler1
        build:
            context: https://github.com/chalmers-revere/opendlv-video-x264-recorder.git#v0.0.1
            dockerfile: Dockerfile.amd64
        restart: always
        ipc: "host"
        network_mode: "host"
        volumes:
        - /tmp:/tmp
        - $HOME/recordings/basler1:/recordings
        working_dir: /recordings
        cap_add:
        - SYS_NICE
        entrypoint: ""
        command: "nice -n -8 /usr/bin/opendlv-video-x264-recorder --id=1 --name=basler1.i420 --width=1024 --height=768"

