# Copyright (C) 2019 Christian Berger
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.

# Date: 2019-03-22

version: '2.3'

# These services run on Brick.
services:
    ###########################################################################
    # Relay Envelopes from CID 109 (dlv-device-cangw-snowfox) to CID 111 via TCP.
    relay-receive-from-109:
        container_name: relay-receive-from-109
        image: chrberger/cluon-relay-multi:v0.0.4
        cpuset: "1"
        restart: always
        network_mode: "host"
        cap_add:
        - SYS_NICE
        entrypoint: ""
        command: "nice -n -6 /usr/bin/cluon-relay --cid-to=111 --via-tcp=10.42.42.1:55109"
        runtime: runc

    ###########################################################################
    # Relay and downsample Envelopes from CID 111 (local CID session on Brick) to CID 110 (for opendlv-vehicle-view).
    relay-downsample-111-110:
        container_name: relay-downsample-111-110
        image: chrberger/cluon-relay-multi:v0.0.4
        cpuset: "2"
        restart: always
        network_mode: "host"
        cap_add:
        - SYS_NICE
        entrypoint: ""
        command: "nice -n -7 /usr/bin/cluon-relay --cid-from=111 --cid-to=110 --downsample=19:10,49:1,1046:10"
        runtime: runc

    ###########################################################################
    # Relay cluon.data.RecorderCommand.
    relay-recordercommand-110-111:
        container_name: relay-recordercommand-110-111
        image: chrberger/cluon-relay-multi:v0.0.4
        cpuset: "2"
        restart: always
        network_mode: "host"
        cap_add:
        - SYS_NICE
        entrypoint: ""
        command: "nice -n -7 /usr/bin/cluon-relay --cid-from=110 --cid-to=111 --keep=11"
        runtime: runc

    ###########################################################################
    # Dump all containers from CID 111 on request.
    record-111:
        container_name: record-111
        image: chrberger/cluon-record-multi:v0.0.1
        cpuset: "1"
        restart: always
        network_mode: "host"
        volumes:
        - $HOME/recordings:/recordings
        working_dir: /recordings
        command: "--cid=111 --remote --recsuffix=-all"
        runtime: runc

    ###########################################################################
    # opendlv-vehicle-view on 110.
    vehicle-view:
        container_name: opendlv-vehicle-view
        image: chalmersrevere/opendlv-vehicle-view-multi:v0.0.59
        cpuset: "1"
        restart: always
        network_mode: "host"
        volumes:
        - $HOME/recordings:/recordings
        - /var/run/docker.sock:/var/run/docker.sock
        environment:
        - OD4SESSION_CID=110
        - PLAYBACK_OD4SESSION_CID=210
        - OPENDLV_VEHICLE_VIEW_PLATFORM=Snowfox
        ports:
        - "8081:8081"
        cap_add:
        - SYS_NICE
        entrypoint: ""
        command: "nice -n -1 node index.js"
        runtime: runc

    ###########################################################################
    # Applanix Ethernet Realtime port on 111.
    dev-gps-pos-rt:
        container_name: dev-gps-pos-rt
        image: chalmersrevere/opendlv-device-gps-pos-multi:v0.0.11
        cpuset: "4"
        restart: always
        network_mode: "host"
        cap_add:
        - SYS_NICE
        entrypoint: ""
        command: "nice -n -5 /usr/bin/opendlv-device-gps-pos --pos_ip=10.42.42.40 --pos_port=5602 --cid=111 --id=0"
        runtime: runc

    # Applanix Ethernet Loggin port on 111.
    dev-gps-pos-log:
        container_name: dev-gps-pos-log
        image: chalmersrevere/opendlv-device-gps-pos-multi:v0.0.11
        cpuset: "5"
        restart: always
        network_mode: "host"
        cap_add:
        - SYS_NICE
        entrypoint: ""
        command: "nice -n -4 /usr/bin/opendlv-device-gps-pos --pos_ip=10.42.42.40 --pos_port=5603 --cid=111 --id=0"
        runtime: runc

    ###########################################################################
    # Trimble GPS.
    dev-gps-nmea:
        container_name: dev-gps-nmea
        image: chalmersrevere/opendlv-device-gps-nmea-multi:v0.0.13
        cpuset: "6"
        restart: always
        network_mode: "host"
        cap_add:
        - SYS_NICE
        entrypoint: ""
        command: "nice -n -3 /usr/bin/opendlv-device-gps-nmea --nmea_ip=10.42.42.41 --nmea_port=9999 --cid=111 --id=1"

    ###########################################################################
    # PEAK GPS.
#    dev-gps-peak:
#        container_name: dev-gps-nmea
#        image: chalmersrevere/opendlv-device-gps-peak-amd64:v0.0.8
#        cpuset: "7"
#        privileged: true
#        restart: always
#        network_mode: "host"
#        cap_add:
#        - SYS_NICE
#        entrypoint: ""
#        command: "nice -n -3 /usr/bin/opendlv-device-gps-peak --cid=111 --id=2 --can=can0"

