# Copyright (C) 2019 Christian Berger
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.

# Date: 2019-06-22

version: '2.3'

# These services run on Brick.
services:
    ###########################################################################
    # Relay Envelopes from CID 109 (dlv-device-cangw-snowfox) to CID 111 via TCP.
    relay-receive-from-109:
        container_name: relay-receive-from-109
        image: chrberger/cluon-relay-multi:v0.0.4
        cpuset: "1"
        restart: always
        network_mode: "host"
        cap_add:
        - SYS_NICE
        entrypoint: ""
        command: "nice -n -6 /usr/bin/cluon-relay --cid-to=111 --via-tcp=10.42.42.1:55109"
        runtime: runc

    ###########################################################################
    # Relay and downsample Envelopes from CID 111 (local CID session on Brick) to CID 110 (for opendlv-vehicle-view).
    relay-downsample-111-110:
        container_name: relay-downsample-111-110
        image: chrberger/cluon-relay-multi:v0.0.4
        cpuset: "2"
        restart: always
        network_mode: "host"
        cap_add:
        - SYS_NICE
        entrypoint: ""
        command: "nice -n -7 /usr/bin/cluon-relay --cid-from=111 --cid-to=110 --downsample=19:10,49:1,1046:10"
        runtime: runc

    ###########################################################################
    # Relay cluon.data.RecorderCommand.
    relay-recordercommand-110-111:
        container_name: relay-recordercommand-110-111
        image: chrberger/cluon-relay-multi:v0.0.4
        cpuset: "1"
        restart: always
        network_mode: "host"
        cap_add:
        - SYS_NICE
        entrypoint: ""
        command: "nice -n -7 /usr/bin/cluon-relay --cid-from=110 --cid-to=111 --keep=11"
        runtime: runc

    ###########################################################################
    # opendlv-vehicle-view on 110.
    vehicle-view:
        container_name: opendlv-vehicle-view
        image: chalmersrevere/opendlv-vehicle-view-multi:v0.0.60
        cpuset: "1"
        restart: always
        network_mode: "host"
        volumes:
        - $HOME/recordings:/opt/vehicle-view/recordings
        - /var/run/docker.sock:/var/run/docker.sock
        environment:
        - OD4SESSION_CID=110
        - PLAYBACK_OD4SESSION_CID=210
        - OPENDLV_VEHICLE_VIEW_PLATFORM=Snowfox
        ports:
        - "8081:8081"
        cap_add:
        - SYS_NICE
        entrypoint: ""
        command: "nice -n -1 node index.js"
        runtime: runc

    ###########################################################################
    # Trimble GPS (check IP)
    dev-gps-nmea:
        container_name: dev-gps-nmea
        image: chalmersrevere/opendlv-device-gps-nmea-multi:v0.0.14
        cpuset: "3"
        restart: always
        network_mode: "host"
        cap_add:
        - SYS_NICE
        entrypoint: ""
        command: "nice -n -3 /usr/bin/opendlv-device-gps-nmea --nmea_ip=10.42.42.41 --nmea_port=9999 --cid=111 --id=1"    

    ###########################################################################
    # Applanix Ethernet Realtime port on 111.
    dev-gps-pos-rt:
        container_name: dev-gps-pos-rt
        image: chalmersrevere/opendlv-device-gps-pos-multi:v0.0.11
        cpuset: "4"
        restart: always
        network_mode: "host"
        cap_add:
        - SYS_NICE
        entrypoint: ""
        command: "nice -n -5 /usr/bin/opendlv-device-gps-pos --pos_ip=10.42.42.40 --pos_port=5602 --cid=111 --id=0"
        runtime: runc

#    # Applanix Ethernet Loggin port on 111 (extensive logging!).
#    dev-gps-pos-log:
#        container_name: dev-gps-pos-log
#        image: chalmersrevere/opendlv-device-gps-pos-multi:v0.0.11
#        cpuset: "5"
#        restart: always
#        network_mode: "host"
#        cap_add:
#        - SYS_NICE
#        entrypoint: ""
#        command: "nice -n -4 /usr/bin/opendlv-device-gps-pos --pos_ip=10.42.42.40 --pos_port=5603 --cid=111 --id=0"
#        runtime: runc

    ###########################################################################
    # Velodyne HDL32 Lidar on 111.
    dev-lidar-hdl32e:
        container_name: dev-lidar-hdl32e
        image: chalmersrevere/opendlv-device-lidar-hdl32e-multi:v0.0.14
        cpuset: "3"
        restart: always
        network_mode: "host"
        cap_add:
        - SYS_NICE
        entrypoint: ""
        command: "nice -n -7 /usr/bin/opendlv-device-lidar-hdl32e --hdl32e_ip=10.42.44.22 --hdl32e_port=2368 --cid=111 --gpstime"
        runtime: runc

    ###########################################################################
    # Axis camera including recording functionality with remote start/stop.
    dev-camera-axis0:
        container_name: dev-camera-axis0
        image: chalmersrevere/opendlv-device-camera-rtp-amd64:2file
        cpuset: "5"
        restart: always
        network_mode: "host"
        volumes:
        - $HOME/recordings:/recordings
        working_dir: /recordings
        cap_add:
        - SYS_NICE
        command: "nice -n -8 /usr/bin/opendlv-device-camera-rtp --url=rtsp://10.42.45.50/axis-media/media.amp\\?camera=1 --cid=111 --id=0 --client-port-udp-a=35000 --remote --recsuffix=-all"
        runtime: runc

    ###########################################################################
    # Basler.
    dev-camera-basler1:
        container_name: dev-camera-basler1
        build:
            context: https://github.com/chalmers-revere/opendlv-device-camera-pylon.git#v0.0.2
            dockerfile: Dockerfile.amd64
        cpuset: "7"
        restart: always
        network_mode: "host"
        ipc: "host"
        environment:
        - DISPLAY=$DISPLAY
        volumes:
        - /tmp:/tmp
        cap_add:
        - SYS_NICE
        entrypoint: ""
        command: "nice -n -8 /usr/bin/opendlv-device-camera-pylon --camera=0 --width=2048 --height=1536 --packetsize=9000 --offsetX=0 --offsetY=0 --autoexposuretimeabslowerlimit=26 --autoexposuretimeabsupperlimit=500 --fps=15 --name.i420=basler1.i420 --name.argb=basler1.argb"
        runtime: runc

    qsv-h264-thumbnail-basler1:
        container_name: qsv-h264-thumbnail-basler1
        image: chrberger/video-qsv-h264-encoder:v0.0.4
        depends_on:
        - dev-camera-basler1
        cpuset: "6"
        devices:
        - /dev/dri/renderD128
        restart: always
        ipc: "host"
        network_mode: "host"
        volumes:
        - /tmp:/tmp
        cap_add:
        - SYS_NICE
        entrypoint: ""
        command: "nice -n -7 /usr/bin/video-qsv-h264-encoder --cid=110 --name=basler1.i420 --width=2048 --height=1536 --id=1 --bitrate=3000 --crop.x=704 --crop.y=500 --crop.width=640 --crop.height=480 --downsample=1"
        runtime: runc

    nvenc-h264-ll-rec-basler1:
        container_name: nvenc-h264-ll-rec-basler1
        image: nvenc-h264-recorder:cuda10.1
        depends_on:
        - dev-camera-basler1
        cpuset: "6"
        init: true
        restart: always
        network_mode: "host"
        ipc: "host"
        volumes:
        - /tmp:/tmp
        - $HOME/recordings:/recordings
        - /usr/lib64/libnvcuvid.so.430.26:/usr/lib/x86_64-linux-gnu/libnvcuvid.so.430.26
        - /usr/lib64/libnvidia-encode.so.430.26:/usr/lib/x86_64-linux-gnu/libnvidia-encode.so.430.26
        working_dir: /recordings
        command: "--name=basler1.i420 --cid=111 --id=1 --width=2048 --height=1536 --remote --recsuffix=-basler1-lossless"
        runtime: nvidia

