version: '2'

services:
    ###########################################################################
    # Basler
    dev-camera-basler:
        container_name: dev-camera-basler
        build:
            context: https://github.com/chalmers-revere/opendlv-device-camera-pylon.git#v0.0.1
            dockerfile: Dockerfile.amd64
        restart: always
        network_mode: "host"
        ipc: "host"
        environment:
        - DISPLAY=$DISPLAY
        volumes:
        - /tmp:/tmp
        cap_add:
        - SYS_NICE
        entrypoint: ""
        command: "nice -n -10 /usr/bin/opendlv-device-camera-pylon --camera=0 --width=1280 --height=768 --offsetX=640 --offsetY=500 --fps=15 --verbose"

