version: '2'

services:
    odsupercomponent:
        container_name: odsupercomponent
        image: seresearch/opendlv-rhino-on-opendlv-on-opendlv-core-on-opendavinci-on-base:v0.1.5
        restart: on-failure
        network_mode: "host"
        volumes:
        - .:/opt/opendlv.data
        cap_add:
        - SYS_NICE
        entrypoint: ""
        command: "nice -n 0 /opt/od4/bin/odsupercomponent --configuration=/opt/opendlv.data/configuration --cid=110"

    # CAN interface to access Snowfox.
    proxy-xc90:
        container_name: proxy-xc90
        image: $DOCKER_IMAGE_PROXY_XC90
        restart: on-failure
        network_mode: "host"
        privileged: true
        depends_on:
        - odsupercomponent
        cap_add:
        - SYS_NICE
        entrypoint: ""
        command: "nice -n -1 /opt/dlv.snowfox/bin/snowfox-proxy-xc90 --freq=100 --cid=110"

    ###########################################################################
    # Web-application for viewing vehicle data.
    vehicle-view:
        container_name: opendlv-vehicle-view
        image: chalmersrevere/opendlv-vehicle-view-multi:v0.0.55
        restart: always
        network_mode: "host"
        volumes:
        - ~/recordings:/opt/vehicle-view/recordings
        - /var/run/docker.sock:/var/run/docker.sock
        environment:
        - OD4SESSION_CID=110
        - PLAYBACK_OD4SESSION_CID=210
        - OPENDLV_VEHICLE_VIEW_PLATFORM=Snowfox        
        ports:
        - "8081:8081"
        cap_add:
        - SYS_NICE
        entrypoint: ""
        command: "nice -n -15 node index.js"


    ###########################################################################
    # GPS devices.
    dev-gps-pos:
        container_name: dev-gps-pos
        image: chalmersrevere/opendlv-device-gps-pos-multi:v0.0.10
        restart: always
        network_mode: "host"
        cap_add:
        - SYS_NICE
        entrypoint: ""
        command: "nice -n -3 /usr/bin/opendlv-device-gps-pos --pos_ip=10.42.42.40 --pos_port=5602 --cid=110 --id=0"


    dev-gps-nmea:
        container_name: dev-gps-nmea
        image: chalmersrevere/opendlv-device-gps-nmea-multi:v0.0.13
        restart: always
        network_mode: "host"
        cap_add:
        - SYS_NICE
        entrypoint: ""
        command: "nice -n -3 /usr/bin/opendlv-device-gps-nmea --nmea_ip=10.42.42.29 --nmea_port=9999 --cid=110 --id=1"


    ###########################################################################
    # Velodyne HDL32 Lidar.
    dev-lidar-hdl32e:
        container_name: dev-lidar-hdl32e
        image: chalmersrevere/opendlv-device-lidar-hdl32e-multi:v0.0.13
        restart: always
        network_mode: "host"
        cap_add:
        - SYS_NICE
        entrypoint: ""
        command: "nice -n -7 /usr/bin/opendlv-device-lidar-hdl32e --hdl32e_ip=0.0.0.0 --hdl32e_port=2368 --cid=110 --gpstime"


    ###########################################################################
    # Axis camera.
    dev-camera-axis0:
        container_name: dev-camera-opencv
        image: chalmersrevere/opendlv-device-camera-opencv-multi:v0.0.10
        restart: always
        ipc: "host"
        network_mode: "host"
        environment:
        - DISPLAY=$DISPLAY
        volumes:
        - /tmp:/tmp
        cap_add:
        - SYS_NICE
        entrypoint: ""
        command: "nice -n -5 /usr/bin/opendlv-device-camera-opencv --camera=http://root:pass@10.42.42.50/axis-cgi/mjpg/video.cgi\\?channel=0\\&.mjpg --width=1280 --height=720 --freq=30 --name.i420=axis0.i420 --name.argb=axis0.argb"

    x264-lossless-recorder-axis0:
        container_name: x264-lossless-recorder-axis0
        build:
            context: https://github.com/chalmers-revere/opendlv-video-x264-recorder.git#v0.0.1
            dockerfile: Dockerfile.amd64
        restart: always
        ipc: "host"
        network_mode: "host"
        volumes:
        - /tmp:/tmp
        - $HOME/recordings:/recordings
        working_dir: /recordings
        cap_add:
        - SYS_NICE
        entrypoint: ""
        command: "nice -n -6 /usr/bin/opendlv-video-x264-recorder --id=2 --name=axis0.i420 --width=1280 --height=720 --rec=2019-01-28_axis0.rec"

    thumbnail-axis0:
        container_name: thumbnail-axis0
        image: chalmersrevere/i420toolbox-amd64:v0.0.1
        restart: always
        ipc: "host"
        environment:
        - DISPLAY=$DISPLAY
        volumes:
        - /tmp:/tmp
        cap_add:
        - SYS_NICE
        entrypoint: ""
        command: "nice -n -2 /usr/bin/i420toolbox --in=axis0.i420 --out=tnaxis0.i420 --in.width=1280 --in.height=720 --crop.x=320 --crop.y=0 --crop.width=640 --crop.height=480"

    x264-lossy-encoder-tnaxis0:
        container_name: x264-lossy-encoder-tnaxis0
        build:
            context: https://github.com/chalmers-revere/opendlv-video-x264-encoder.git
            dockerfile: Dockerfile.amd64
        restart: always
        network_mode: "host"
        ipc: "host"
        volumes:
        - /tmp:/tmp
        cap_add:
        - SYS_NICE
        entrypoint: ""
        command: "nice -n -10 /usr/bin/opendlv-video-x264-encoder --cid=110 --name=tnaxis0.i420 --width=640 --height=480 --id=0"


