# Copyright (C) 2019 Christian Berger
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.

# Date: 2019-02-14

version: '2.3'

services:
    ###########################################################################
    # Axis camera.
    dev-camera-axis0:
        container_name: dev-camera-opencv
        image: chalmersrevere/opendlv-device-camera-opencv-multi:v0.0.11
        cpuset: "5"
        restart: always
        ipc: "host"
        network_mode: "host"
        environment:
        - DISPLAY=$DISPLAY
        volumes:
        - /tmp:/tmp
        cap_add:
        - SYS_NICE
        entrypoint: ""
        command: "nice -n -8 /usr/bin/opendlv-device-camera-opencv --camera=http://root:pass@10.42.45.50/axis-cgi/mjpg/video.cgi\\?channel=0\\&.mjpg --width=1280 --height=720 --freq=30 --name.i420=axis0.i420 --name.argb=axis0.argb"
        runtime: runc

    nvenc-h264-ll-rec-axis0:
        container_name: nvenc-h264-ll-rec-axis0
        image: nvenc-h264:latest
        depends_on:
        - dev-camera-axis0
        cpuset: "5"
        restart: always
        ipc: "host"
        privileged: true
        network_mode: "host"
        volumes:
        - /tmp:/tmp
        - $HOME/recordings:/recordings
        working_dir: /recordings
        cap_add:
        - SYS_NICE
        entrypoint: ""
        command: "nice -n -7 /usr/bin/video-nvenc-h264-recorder --id=0 --name=axis0.i420 --width=1280 --height=720 --recsuffix=axis0-lossless --verbose"
        runtime: nvidia

