# Copyright (C) 2019 Christian Berger
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.

# Date: 2019-02-06

version: '2.2'

services:
    # Monitor netload.
    monitor-netload:
        container_name: monitor-netload
        build:
            context: .
            dockerfile: Dockerfile.amd64
        cpuset: "1"
        init: true
        volumes:
        - /run/media/brick/RevereData1/brick/recordings:/recordings
        working_dir: /recordings
        restart: always
        network_mode: "host"
        command: "/usr/bin/monitor-netload.sh enp10s0,enp11s0,enp5s0,enp4s0"

    # Monitor sysload.
    monitor-sysload:
        container_name: monitor-sysload
        build:
            context: .
            dockerfile: Dockerfile.amd64
        cpuset: "1"
        init: true
        pid: "host"
        volumes:
        - /run/media/brick/RevereData1/brick/recordings:/recordings
        working_dir: /recordings
        restart: always
        network_mode: "host"
        command: "/usr/bin/monitor-sysload.sh 1 2 3 4 5 6 7"

    ###########################################################################
    # Relay Envelopes from CID 109 (dlv-device-cangw-snowfox) to CID 111.
    relay-109-111:
        container_name: forward-109-111
        image: chrberger/cluon-relay-multi:v0.0.2
        cpuset: "1"
        restart: always
        network_mode: "host"
        cap_add:
        - SYS_NICE
        entrypoint: ""
        command: "nice -n -6 /usr/bin/cluon-relay --cid-from=109 --cid-to=111"

    ###########################################################################
    # Relay and downsample Envelopes from CID 111 (local CID session on Brick) to CID 110 (for opendlv-vehicle-view).
    relay-downsample-111-110:
        container_name: relay-downsample-111-110
        image: chrberger/cluon-relay-multi:v0.0.2
        cpuset: "2"
        restart: always
        network_mode: "host"
        cap_add:
        - SYS_NICE
        entrypoint: ""
        command: "nice -n -7 /usr/bin/cluon-relay --cid-from=111 --cid-to=110 --downsample=19:10,49:1,1046:10"

    ###########################################################################
    # Dump all containers from CID 111.
    record-111:
        container_name: record-111
        image: chrberger/cluon-amd64:latest
        cpuset: "1"
        restart: always
        network_mode: "host"
        volumes:
        - /run/media/brick/RevereData1/brick/recordings:/recordings
        working_dir: /recordings
        cap_add:
        - SYS_NICE
        command: sh -c "nice -n -7 cluon-OD4toStdout --cid=111 > `date +CID-111-recording-%Y-%m-%d_%H%M%S.rec`"

    ###########################################################################
    # opendlv-vehicle-view on 110.
    vehicle-view:
        container_name: opendlv-vehicle-view
        image: chalmersrevere/opendlv-vehicle-view-multi:v0.0.57
        cpuset: "1"
        restart: always
        network_mode: "host"
        volumes:
        - ~/recordings:/opt/vehicle-view/recordings
        - /var/run/docker.sock:/var/run/docker.sock
        environment:
        - OD4SESSION_CID=110
        - PLAYBACK_OD4SESSION_CID=210
        - OPENDLV_VEHICLE_VIEW_PLATFORM=Snowfox
        ports:
        - "8081:8081"
        cap_add:
        - SYS_NICE
        entrypoint: ""
        command: "nice -n -1 node index.js"

    # Applanix Ethernet Realtime port on 111.
    dev-gps-pos-rt:
        container_name: dev-gps-pos-rt
        image: chalmersrevere/opendlv-device-gps-pos-multi:v0.0.11
        cpuset: "3"
        restart: always
        network_mode: "host"
        cap_add:
        - SYS_NICE
        entrypoint: ""
        command: "nice -n -5 /usr/bin/opendlv-device-gps-pos --pos_ip=10.42.42.40 --pos_port=5602 --cid=111 --id=0"

    # Applanix Ethernet Loggin port on 111.
    dev-gps-pos-log:
        container_name: dev-gps-pos-log
        image: chalmersrevere/opendlv-device-gps-pos-multi:v0.0.11
        cpuset: "4"
        restart: always
        network_mode: "host"
        cap_add:
        - SYS_NICE
        entrypoint: ""
        command: "nice -n -4 /usr/bin/opendlv-device-gps-pos --pos_ip=10.42.42.40 --pos_port=5603 --cid=111 --id=0"

    ###########################################################################
    # Velodyne HDL32 Lidar on 111.
    dev-lidar-hdl32e:
        container_name: dev-lidar-hdl32e
        image: chalmersrevere/opendlv-device-lidar-hdl32e-multi:v0.0.14
        cpuset: "2"
        restart: always
        network_mode: "host"
        cap_add:
        - SYS_NICE
        entrypoint: ""
        command: "nice -n -7 /usr/bin/opendlv-device-lidar-hdl32e --hdl32e_ip=10.42.44.22 --hdl32e_port=2368 --cid=111 --gpstime"

    ###########################################################################
    # Axis camera.
    dev-camera-axis0:
        container_name: dev-camera-opencv
        image: chalmersrevere/opendlv-device-camera-opencv-multi:v0.0.11
        cpuset: "5"
        restart: always
        ipc: "host"
        network_mode: "host"
        environment:
        - DISPLAY=$DISPLAY
        volumes:
        - /tmp:/tmp
        cap_add:
        - SYS_NICE
        entrypoint: ""
        command: "nice -n -8 /usr/bin/opendlv-device-camera-opencv --camera=http://root:pass@10.42.45.50/axis-cgi/mjpg/video.cgi\\?channel=0\\&.mjpg --width=1280 --height=720 --freq=30 --name.i420=axis0.i420 --name.argb=axis0.argb"

#    nvenc-h264-ll-rec-axis0:
#        container_name: nvenc-h264-ll-rec-axis0
#        image: nvenc-h264:latest
#        depends_on:
#        - dev-camera-axis0
#        cpuset: "5"
#        restart: always
#        ipc: "host"
#        privileged: true
#        network_mode: "host"
#        volumes:
#        - /tmp:/tmp
#        - /run/media/brick/RevereData1/brick/recordings:/recordings
#        working_dir: /recordings
#        cap_add:
#        - SYS_NICE
#        entrypoint: ""
#        command: "nice -n -7 /usr/bin/video-nvenc-h264-recorder --id=0 --name=axis0.i420 --width=1280 --height=720 --recsuffix=axis0-lossless"

    ###########################################################################
    # Basler.
    dev-camera-basler1:
        container_name: dev-camera-basler1
        build:
            context: https://github.com/chalmers-revere/opendlv-device-camera-pylon.git#v0.0.1
            dockerfile: Dockerfile.amd64
        cpuset: "7"
        restart: always
        network_mode: "host"
        ipc: "host"
        environment:
        - DISPLAY=$DISPLAY
        volumes:
        - /tmp:/tmp
        cap_add:
        - SYS_NICE
        entrypoint: ""
        command: "nice -n -8 /usr/bin/opendlv-device-camera-pylon --camera=0 --width=2048 --height=1536 --offsetX=0 --offsetY=0 --name.i420=basler1.i420 --name.argb=basler1.argb"

#    nvenc-h264-ll-rec-basler1:
#        container_name: nvenc-h264-ll-rec-basler1
#        image: nvenc-h264:latest
#        depends_on:
#        - dev-camera-basler1
#        cpuset: "6"
#        restart: always
#        ipc: "host"
#        privileged: true
#        network_mode: "host"
#        volumes:
#        - /tmp:/tmp
#        - /run/media/brick/RevereData1/brick/recordings:/recordings
#        working_dir: /recordings
#        cap_add:
#        - SYS_NICE
#        entrypoint: ""
#        command: "nice -n -7 /usr/bin/video-nvenc-h264-recorder --id=1 --name=basler1.i420 --width=2048 --height=1536 --recsuffix=basler1-lossless --verbose"

