version: '2'

services:
    odsupercomponent:
        container_name: odsupercomponent
        image: seresearch/opendlv-rhino-on-opendlv-on-opendlv-core-on-opendavinci-on-base:v0.1.5
        restart: on-failure
        network_mode: "host"
        volumes:
        - .:/opt/opendlv.data
        cap_add:
        - SYS_NICE
        entrypoint: ""
        command: "nice -n 0 /opt/od4/bin/odsupercomponent --configuration=/opt/opendlv.data/configuration --cid=110"

    # CAN interface to access Snowfox.
    proxy-xc90:
        container_name: proxy-xc90
        image: $DOCKER_IMAGE_PROXY_XC90
        restart: on-failure
        network_mode: "host"
        privileged: true
        depends_on:
        - odsupercomponent
        cap_add:
        - SYS_NICE
        entrypoint: ""
        command: "nice -n -1 /opt/dlv.snowfox/bin/snowfox-proxy-xc90 --freq=100 --cid=110"

    ###########################################################################
    # Web-application for viewing vehicle data.
    vehicle-view:
        container_name: opendlv-vehicle-view
        image: chalmersrevere/opendlv-vehicle-view-multi:v0.0.55
        restart: always
        network_mode: "host"
        volumes:
        - ~/recordings:/opt/vehicle-view/recordings
        - /var/run/docker.sock:/var/run/docker.sock
        environment:
        - OD4SESSION_CID=110
        - PLAYBACK_OD4SESSION_CID=210
        - OPENDLV_VEHICLE_VIEW_PLATFORM=Snowfox
        ports:
        - "8081:8081"
        cap_add:
        - SYS_NICE
        entrypoint: ""
        command: "nice -n -15 node index.js"


    ###########################################################################
    # GPS devices.
    dev-gps-pos-rt:
        container_name: dev-gps-pos-rt
        image: chalmersrevere/opendlv-device-gps-pos-multi:v0.0.11
        restart: always
        network_mode: "host"
        cap_add:
        - SYS_NICE
        entrypoint: ""
        command: "nice -n -3 /usr/bin/opendlv-device-gps-pos --pos_ip=10.42.42.40 --pos_port=5602 --cid=110 --id=0"
    dev-gps-pos-log:
        container_name: dev-gps-pos-log
        image: chalmersrevere/opendlv-device-gps-pos-multi:v0.0.11
        restart: always
        network_mode: "host"
        cap_add:
        - SYS_NICE
        entrypoint: ""
        command: "nice -n -3 /usr/bin/opendlv-device-gps-pos --pos_ip=10.42.42.40 --pos_port=5603 --cid=110 --id=0"

    dev-gps-nmea:
        container_name: dev-gps-nmea
        image: chalmersrevere/opendlv-device-gps-nmea-multi:v0.0.13
        restart: always
        network_mode: "host"
        cap_add:
        - SYS_NICE
        entrypoint: ""
        command: "nice -n -3 /usr/bin/opendlv-device-gps-nmea --nmea_ip=10.42.42.29 --nmea_port=9999 --cid=110 --id=1"


    ###########################################################################
    # Velodyne HDL32 Lidar.
    dev-lidar-hdl32e:
        container_name: dev-lidar-hdl32e
        image: chalmersrevere/opendlv-device-lidar-hdl32e-multi:v0.0.13
        restart: always
        network_mode: "host"
        cap_add:
        - SYS_NICE
        entrypoint: ""
        command: "nice -n -7 /usr/bin/opendlv-device-lidar-hdl32e --hdl32e_ip=0.0.0.0 --hdl32e_port=2368 --cid=110 --gpstime"

