version: '2'

services:
    ###########################################################################
    # BoB.
    dev-camera-bob2:
        container_name: dev-camera-bob2
        image: $DOCKER_IMAGE_DEV_CAMERA_BOB
        restart: always
        ipc: "host"
        network_mode: "host"
        environment:
        - DISPLAY=$DISPLAY
        volumes:
        - /tmp:/tmp
        cap_add:
        - SYS_NICE
        entrypoint: ""
        command: "nice -n -5 /usr/bin/dlv-device-camera-bob --cid=110 --hostip=192.168.1.1 --bobip=192.168.1.2 --name.i420=bob2.i420 --name.argb=bob2.argb"

    x264-ll-rec-bob2:
        container_name: x264-lossless-recorder-bob2
        build:
            context: https://github.com/chalmers-revere/opendlv-video-x264-recorder.git#v0.0.1
            dockerfile: Dockerfile.amd64
        restart: always
        ipc: "host"
        network_mode: "host"
        volumes:
        - /tmp:/tmp
        - $HOME/recordings/bob2:/recordings
        working_dir: /recordings
        cap_add:
        - SYS_NICE
        entrypoint: ""
        command: "nice -n -6 /usr/bin/opendlv-video-x264-recorder --id=2 --name=bob2.i420 --width=1104 --height=624"

    thumbnail-bob2:
        container_name: thumbnail-bob2
        image: chalmersrevere/i420toolbox-amd64:v0.0.2
        restart: always
        ipc: "host"
        environment:
        - DISPLAY=$DISPLAY
        volumes:
        - /tmp:/tmp
        cap_add:
        - SYS_NICE
        entrypoint: ""
        command: "nice -n -3 /usr/bin/i420toolbox --in=bob2.i420 --out=tnbob2.i420 --in.width=1104 --in.height=624 --crop.x=232 --crop.y=72 --crop.width=640 --crop.height=480"

    x264-lsy-enc-tnbob2:
        container_name: x264-lossy-encoder-tnbob2
        build:
            context: https://github.com/chalmers-revere/opendlv-video-x264-encoder.git
            dockerfile: Dockerfile.amd64
        restart: always
        network_mode: "host"
        ipc: "host"
        volumes:
        - /tmp:/tmp
        cap_add:
        - SYS_NICE
        entrypoint: ""
        command: "nice -n -4 /usr/bin/opendlv-video-x264-encoder --cid=110 --name=tnbob2.i420 --width=640 --height=480 --id=2"

    ###########################################################################
    # Basler.
    dev-camera-basler1:
        container_name: dev-camera-basler1
        build:
            context: https://github.com/chalmers-revere/opendlv-device-camera-pylon.git#v0.0.1
            dockerfile: Dockerfile.amd64
        restart: always
        network_mode: "host"
        ipc: "host"
        environment:
        - DISPLAY=$DISPLAY
        volumes:
        - /tmp:/tmp
        cap_add:
        - SYS_NICE
        entrypoint: ""
        command: "nice -n -7 /usr/bin/opendlv-device-camera-pylon --camera=0 --width=1024 --height=768 --offsetX=640 --offsetY=500 --fps=15 --name.i420=basler1.i420 --name.argb=basler1.argb"

    x264-ll-rec-basler1:
        container_name: x264-lossless-recorder-basler1
        build:
            context: https://github.com/chalmers-revere/opendlv-video-x264-recorder.git#v0.0.1
            dockerfile: Dockerfile.amd64
        restart: always
        ipc: "host"
        network_mode: "host"
        volumes:
        - /tmp:/tmp
        - $HOME/recordings/basler1:/recordings
        working_dir: /recordings
        cap_add:
        - SYS_NICE
        entrypoint: ""
        command: "nice -n -8 /usr/bin/opendlv-video-x264-recorder --id=1 --name=basler1.i420 --width=1024 --height=768"

    thumbnail-basler1:
        container_name: thumbnail-basler1
        image: chalmersrevere/i420toolbox-amd64:v0.0.2
        restart: always
        ipc: "host"
        environment:
        - DISPLAY=$DISPLAY
        volumes:
        - /tmp:/tmp
        cap_add:
        - SYS_NICE
        entrypoint: ""
        command: "nice -n -3 /usr/bin/i420toolbox --in=basler1.i420 --out=tnbasler1.i420 --in.width=1024 --in.height=768 --crop.x=192 --crop.y=144 --crop.width=640 --crop.height=480"

    x264-lsy-enc-tnbasler1:
        container_name: x264-lossy-encoder-tnbasler1
        build:
            context: https://github.com/chalmers-revere/opendlv-video-x264-encoder.git
            dockerfile: Dockerfile.amd64
        restart: always
        network_mode: "host"
        ipc: "host"
        volumes:
        - /tmp:/tmp
        cap_add:
        - SYS_NICE
        entrypoint: ""
        command: "nice -n -4 /usr/bin/opendlv-video-x264-encoder --cid=110 --name=tnbasler1.i420 --width=640 --height=480 --id=1"

